### ISSUE TITLE
Foxglove websocket compatibility?

### ISSUE THREAD

**Issue by MCFurry** [danclapp4/ros2-parameter-extension#2]
Hi there,

I just found this repo via: https://github.com/foxglove/community/issues/198
I just did a quick test and this looks like a very useful panel!

How much effort would you estimate it is, to make your panel also working via Foxglove websocket?

**Comment by MCFurry** [comment]
So to answer my own question, there's no real need to change any code. One just needs to make sure rosapi is running on your robot system, such that the service `/rosapi/nodes` is available.
For the rest the plugin works nicely via Foxglove websocket as well!

p.s.
please have a look here as well: https://github.com/danclapp4/ros2-parameter-extension/pull/3
We noticed the unsorted list is getting inconvenient on a bigger system.

**Comment by Timple** [comment]
In that case you might want to open a PR modifying only the readme :wink:

**Comment by MCFurry** [comment]
> In that case you might want to open a PR modifying only the readme 😉

https://github.com/danclapp4/ros2-parameter-extension/pull/4
